# Generated by Django 3.2.6 on 2021-08-27 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Shop', '0001_initial'),
        ('App_Order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_food', models.BooleanField(default=False)),
                ('admin_check', models.BooleanField(default=False)),
                ('review_food', models.TextField(max_length=1000, null=True, verbose_name='Review')),
                ('rating', models.IntegerField(choices=[(1, 'Worst'), (2, 'Not Bad'), (3, 'Good'), (4, 'Better'), (5, 'Delicious')], null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Shop.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed', models.BooleanField(default=False)),
                ('review_order', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Review Order')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Order.order')),
                ('orderitems', models.ManyToManyField(to='App_Review.Review_Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
